In [1]:
import numpy as np
from numpy.random import randn

numpy.random -> generate a random number from numpy package

numpy is a package, random is a module and randn is a function.

In [2]:
x = randn()
x

-1.1542287243790676

In [3]:
if x > 0.5:
    print("Greater than 1")
else:
    print("Less than 1")

Less than 1


In [4]:
my_list = [0,1,2,3,4]
my_list

[0, 1, 2, 3, 4]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.random.randint(0,10)

7

In [12]:
np.random.randint(0,10,(3,3))

array([[9, 6, 2],
       [1, 2, 9],
       [3, 7, 1]])

In [13]:
np.random.randint(0,100,10)

array([42, 67, 67, 83, 35,  8, 89, 30, 49,  6])

In [16]:
np.random.seed(12)
arr=np.random.randint(0,100,10)

In [17]:
arr

array([75, 27,  6,  2,  3, 67, 76, 48, 22, 49])

np.random.seed() will not give random vslues

In [18]:
arr.max()

76

In [19]:
arr.min()

2

In [20]:
arr.mean()

37.5

In [21]:
arr.reshape(2,5)

array([[75, 27,  6,  2,  3],
       [67, 76, 48, 22, 49]])

np we will get  mean value but not median mode

In [23]:
mat=np.arange(0,100).reshape(10,10)

In [24]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
row=4
col=2
mat[row,col]

42

In [26]:
mat[:,col]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [27]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [32]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])